connection_params:
  ros__parameters:

    connection_type: 'TCP'
    robot: 'KMR'

lbr_command_node:
  ros__parameters:
    id: '1' # Robot ID
    port: '50007'
    KMR/ip: '127.0.0.1'

kmp_command_node:
  ros__parameters:
    id: '1' # Robot ID
    port: '50008'
    KMR/ip: '127.0.0.1'

hybrid_node:
  
  ros__parameters:
    domain: '0.0.0.0'